#http://sirile.github.io/2015/05/18/using-haproxy-and-consul-for-dynamic-service-discovery-on-docker.html
#export DOCKER_MACHINE_IP=$(ifconfig docker0 | grep "inet " | awk -F'[: ]+' '{ print $4 }')

version: '2'

services:

    consul-server:
      image: progrium/consul
      container_name: consul.service.consul
      ports:
        - 8300:8300
        - 8301:8301
        - 8302:8302
        - 8400:8400
        - 8500:8500
        - 53:53
      command: "-server -advertise $DOCKER_MACHINE_IP -bootstrap-expect 1"

    registrator:
      image: gliderlabs/registrator:v7
      container_name: registrator
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
      command: "consul://$DOCKER_MACHINE_IP:8500/"
      links:
        - consul-server

    haproxy:
      image: sirile/haproxy
      container_name: haproxy
      restart: always
      dns:
        - 172.17.42.1
      ports:
        - 80:80
        - 1936:1936
      environment:
        - SERVICE_NAME=haproxy
      links:
        - registrator

    scala-boot-test:
      image: sirile/scala-boot-test
      ports:
        - 80
      environment:
        - SERVICE_TAGS=bootApp

#    nginx:
#      image: nginx:1.13.8-alpine-perl
#      container_name: nginx
#      restart: always
#      dns:
#        - 172.17.42.1
#      ports:
#        - 8080:8080
##      command: [nginx-debug, '-g', 'daemon off;']
#      links:
#        - registrator

#    mongo-db:
#      image: mvertes/alpine-mongo:3.6.1-1
#      container_name: mongo-db
#      restart: always
#      ports:
#        - 27017:27017
#
#    mongo-admin:
#      image: mrvautin/adminmongo
#      container_name: mongo-admin
#      restart: always
#      ports:
#        - 1234:1234
#      depends_on:
#        - mongo-db
#
#    app:
#      image: falconio-assessment
#      restart: always
#      ports:
#        - 8080
#      environment:
#        - SPRING_APPLICATION_NAME=app
#        - SPRING_DATA_MONGODB_HOST=mongo-db
#        - SPRING_CLOUD_CONSUL_HOST=consul.service.consul
#        - SPRING_CLOUD_CONSUL_DISCOVERY_TAGS=bootApp
