version: '2'

services:

    mongo-db:
      image: mvertes/alpine-mongo:3.6.1-1
      container_name: mongo-db
      restart: always
      ports:
        - 27017:27017

    mongo-admin:
      image: mrvautin/adminmongo
      container_name: mongo-admin
      restart: always
      ports:
        - 1234:1234
      depends_on:
        - mongo-db

    nginx:
      image: nginx:1.13.8-alpine-perl
      container_name: nginx
      restart: always
      ports:
        - 8080:8080
      volumes:
        - $PWD/docker/nginx.conf:/etc/nginx/nginx.conf:ro
      command: [nginx-debug, '-g', 'daemon off;']

    consul-server:
      image: gliderlabs/consul-server:0.6
      container_name: consul-server
      ports:
        - 8500:8500
      command: "-node consul-server -bootstrap"

    app1:
      image: falconio-assessment
      container_name: app1
      restart: always
      ports:
        - 8010:8010
      environment:
        - SERVER_PORT=8010
        - SPRING_APPLICATION_NAME=app1
        - SPRING_DATA_MONGODB_HOST=mongo-db
        - SPRING_CLOUD_CONSUL_HOST=consul-server

    app2:
      image: falconio-assessment
      container_name: app2
      restart: always
      ports:
        - 8020:8020
      environment:
        - SERVER_PORT=8020
        - SPRING_APPLICATION_NAME=app2
        - SPRING_DATA_MONGODB_HOST=mongo-db
        - SPRING_CLOUD_CONSUL_HOST=consul-server
